# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Capsule < Formula
  desc "Terminal podcast client for Capsule"
  homepage "https://capsulefm.io"
  version "0.0.2"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/Daio-io/homebrew-capsule-tap/releases/download/v0.0.2/capsule_darwin_amd64.tar.gz"
    sha256 "66e6f461ea82d810596ce3753aed09d3336e1173a9d6d3635e1bec047ec74d8b"

    define_method(:install) do
      bin.install "capsule"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/Daio-io/homebrew-capsule-tap/releases/download/v0.0.2/capsule_darwin_arm64.tar.gz"
    sha256 "6eb465c79ae3df89c0cd50021bf1e0c391e9b385edafe238e4e5968764a0b023"

    define_method(:install) do
      bin.install "capsule"
    end
  end

  test do
    system "#{bin}/capsule", "--version"
  end
end
